### ISSUE TITLE
"sk add" with dependencies

### ISSUE THREAD

**Issue by dgroot** [matthewcarlucci/scikick#2]
When using "sk add" to add a new .Rmd that has a dependency, the command does not work as expected. If the dependency is listed before the target .Rmd to be added, scikick doesn't detect the new .Rmd file.

I.e. the command
`sk add -d code/import.rmd code/analysis.rmd`

returns

```
usage: sk add [-h] [-d DEPS [DEPS ...]] [--copy-deps COPY_DEPS] [--force] rmd [rmd ...]
sk add: error: the following arguments are required: rmd
```

even though it appears that you should be able to list the dependency first.

My assumption is that this is because you are able to list multiple dependencies with "-d" so scikick is reading all the .Rmds as dependencies and missing that analysis.rmd is the target file to be added.

**Comment by dgroot** [comment]
(maybe just updating the documentation to match the expected behaviour would be best?)

**Comment by matthewcarlucci** [comment]
Thanks for the report! The same error occurs in `sk del`. 

```bash
sk del -d code/pca.Rmd code/pc_score_statistics.Rmd
usage: sk del [-h] [-d DEPS [DEPS ...]] rmd [rmd ...]
sk del: error: the following arguments are required: rmd
```

This can be "fixed" with `--`:
```bash
sk del -d code/pca.Rmd -- code/pc_score_statistics.Rmd
```
But it's not very nice.

It looks like use of `nargs="+"` with positional arguments is known to have this issue (https://stackoverflow.com/questions/36328769/argparse-nargs-is-eating-positional-argument). **Removing use of multiple `-d` sounds pretty reasonable.** It's causing the issue and the use cases for multiple `-d` can be done in other ways. I will modify it so multiple `-d` can be accepted as `-d code/import.rmd -d code/import2.rmd` and wildcards can use quotes as `-d "code/import*.rmd"` (quoted so expansion can be done by scikick not shell).

**Comment by dgroot** [comment]
Makes sense! I agree, your solution seems the best option.
